services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - matcha

  front:
    build: docker/front
    container_name: matcha_front
    image: matcha_front
    networks:
      - matcha
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ${PWD}/srcs/front:/var/www/html
      # - matcha_vol_front:/var/www/html
    env_file: .env

  back:
    build: docker/back
    container_name: matcha_back
    image: matcha_back
    networks:
      - matcha
    ports:
      - 8081:8080
      - 5001:5000
    restart: on-failure
    volumes:
      - ${PWD}/srcs/back:/var/www/html
    env_file: .env

  database:
    image: postgres
    container_name: database
    networks:
      - matcha
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
    # volumes:
    #   - vol_database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - matcha
    # volumes:
    #   - redis_data:/data 
    restart: on-failure
    command: redis-server --appendonly yes


networks:
  matcha:
    driver: bridge

# volumes:
#   matcha_vol_front:
#     driver_opts:
#       o: bind
#       type: none
#       device: ${PWD}/srcs/front
#   redis_data:
